# Generated by Django 5.0.1 on 2024-03-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='user',
        ),
        migrations.AlterField(
            model_name='theme',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
